LogLevel warn
MaxLogSize 0
Listen 0.0.0.0:631
Browsing Off
WebInterface No
DefaultAuthType Basic
SystemGroup root
<Location />
  Order allow,deny
  Allow all
</Location>
<Location /admin>
  Order allow,deny
  Allow localhost
</Location>
<Policy default>
  <Limit Create-Job Print-Job Print-URI Validate-Job Get-Jobs Get-Printer-Attributes Send-Document Send-URI>
    Order allow,deny
    Allow all
  </Limit>
  <Limit CUPS-Add-Modify-Printer CUPS-Delete-Printer CUPS-Set-Default>
    Order allow,deny
    Allow localhost
  </Limit>
  <Limit Cancel-Job Hold-Job Release-Job Restart-Job Purge-Jobs Set-Job-Attributes CUPS-Move-Job>
    Require user @OWNER @SYSTEM
    Order deny,allow
  </Limit>
  <Limit All>
    Order deny,allow
  </Limit>
</Policy>
